apiVersion: v1
kind: Secret
metadata:
  name: registry-s3-credentials
  namespace: mlops-registry
type: Opaque
data:
  s3AccessKey: MjJiMGY0NmQwNmU2ZTNiNjg0MjgyNzJhZTk0NjdlNmM=
  s3SecretKey: Y2VmNTNhYjIwNThhMjlmYjc2ZGU0NzY1ZTcxY2VjZTE=