# Feast Feature Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-feature-server
  namespace: mlops-feast
  labels:
    app: feast-feature-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feast-feature-server
  template:
    metadata:
      labels:
        app: feast-feature-server
    spec:
      containers:
      - name: feature-server
        image: feastdev/feature-server:0.40.1
        imagePullPolicy: IfNotPresent
        args:
        - "serve"
        - "-h"
        - "0.0.0.0"
        - "-p"
        - "6566"
        ports:
        - containerPort: 6566
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: feast-config
          mountPath: /app/feature_repo
          readOnly: true
        env:
        - name: FEAST_USAGE
          value: "False"
      volumes:
      - name: feast-config
        configMap:
          name: feast-config
---
apiVersion: v1
kind: Service
metadata:
  name: feast-feature-server
  namespace: mlops-feast
  labels:
    app: feast-feature-server
spec:
  type: NodePort
  ports:
  - port: 6566
    targetPort: 6566
    nodePort: 30060
    name: http
  selector:
    app: feast-feature-server
