# Feast UI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-ui
  namespace: mlops-feast
  labels:
    app: feast-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feast-ui
  template:
    metadata:
      labels:
        app: feast-ui
    spec:
      containers:
      - name: feast-ui
        image: feastdev/feast-ui:0.40.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: FEAST_FEATURE_SERVER_URL
          value: "http://feast-feature-server.mlops-feast.svc.cluster.local:6566"
        volumeMounts:
        - name: feast-config
          mountPath: /app/feature_repo
          readOnly: true
      volumes:
      - name: feast-config
        configMap:
          name: feast-config
---
apiVersion: v1
kind: Service
metadata:
  name: feast-ui
  namespace: mlops-feast
  labels:
    app: feast-ui
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30061
    name: http
  selector:
    app: feast-ui
