# ArgoCD Application: Feast Feature Store
# Official Feast Helm chart for feature serving with UI
# Requires: feast-postgresql, feast-redis (deployed separately)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feast
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: mlops-infrastructure

  source:
    repoURL: https://feast-helm-charts.storage.googleapis.com
    chart: feast-feature-server
    targetRevision: 0.59.0
    helm:
      releaseName: feast
      values: |
        replicaCount: 1

        image:
          repository: feastdev/feature-server
          pullPolicy: IfNotPresent
          tag: "0.46.0"

        logLevel: "INFO"

        # Feast deployment mode: online, offline, ui, registry
        feast_mode: "ui"

        # Base64 encoded feature_store.yaml
        # Decoded config:
        #   project: mlops_features
        #   provider: local
        #   registry:
        #     registry_type: sql
        #     path: postgresql+psycopg://feast:***@feast-postgresql.mlops-feast.svc.cluster.local:5432/feast_registry
        #   online_store:
        #     type: redis
        #     connection_string: feast-redis-master.mlops-feast.svc.cluster.local:6379,password=***
        #   entity_key_serialization_version: 2
        # NOTE: Password special char '!' must be URL-encoded as '%21' in the connection string
        feature_store_yaml_base64: "cHJvamVjdDogbWxvcHNfZmVhdHVyZXMKcHJvdmlkZXI6IGxvY2FsCnJlZ2lzdHJ5OgogIHJlZ2lzdHJ5X3R5cGU6IHNxbAogIHBhdGg6IHBvc3RncmVzcWwrcHN5Y29wZzovL2ZlYXN0OjRrMHBZdTRKTWNabEc4S1BGZWFzdCUyMUBmZWFzdC1wb3N0Z3Jlc3FsLm1sb3BzLWZlYXN0LnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvZmVhc3RfcmVnaXN0cnkKb25saW5lX3N0b3JlOgogIHR5cGU6IHJlZGlzCiAgY29ubmVjdGlvbl9zdHJpbmc6IGZlYXN0LXJlZGlzLW1hc3Rlci5tbG9wcy1mZWFzdC5zdmMuY2x1c3Rlci5sb2NhbDo2Mzc5LHBhc3N3b3JkPTRrMHBZdTRKTWNabEc4S1BGZWFzdFJlZGlzIQplbnRpdHlfa2V5X3NlcmlhbGl6YXRpb25fdmVyc2lvbjogMgo="

        service:
          type: NodePort
          port: 6566

        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30

        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-feast

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
