# ArgoCD Application: Feast Feature Store
# Feature store for ML features with UI, PostgreSQL registry, and Redis online store
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feast
  namespace: mlops-ci
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: mlops-infrastructure

  source:
    repoURL: https://github.com/MosesDastmard/maine-mlops-infra.git
    targetRevision: HEAD
    path: services/feast

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-feast

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
