# ArgoCD Application: Jenkins
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: mlops-ci
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mlops-infrastructure

  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.3
    helm:
      releaseName: jenkins
      values: |
        persistence:
          enabled: true
          storageClass: local-path
          size: 20Gi
          accessMode: ReadWriteOnce

        controller:
          serviceType: NodePort
          nodePort: 30080
          admin:
            username: admin
            password: Moses1749
          installPlugins:
            - kubernetes:4380.v4ab11c8c62e8
            - workflow-aggregator:600.vb_57cdd26fdd7
            - git:5.7.0
            - configuration-as-code:1963.v24e046127a_3f

        agent:
          enabled: true
          image:
            registry: docker.io
            repository: jenkins/inbound-agent
            tag: 4.13-1
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          javaOpts: "-Xmx2g -Xms1g"

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-ci

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
