# ArgoCD Application: Jenkins
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mlops-infrastructure

  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.117
    helm:
      releaseName: jenkins
      values: |
        persistence:
          enabled: true
          storageClass: local-path
          size: 20Gi
          accessMode: ReadWriteOnce

        controller:
          serviceType: NodePort
          nodePort: 30080
          admin:
            username: admin
            password: 4k0pYu4JMcZlG8KP
          installPlugins:
            - kubernetes:4355.vb_3c9f94fc12e
            - workflow-aggregator:608.v67378e9d3110
            - git:5.7.0
            - configuration-as-code:1932.v75cb_b_f1b_698d
            - credentials-binding:696.v28c15ce88064
            - generic-webhook-trigger:2.2.1

        agent:
          enabled: true
          image:
            registry: docker.io
            repository: jenkins/inbound-agent
            tag: 3345.va_ca_72ea_ce92f-1
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          javaOpts: "-Xmx2g -Xms1g"
          podTemplates:
            kaniko: |
              - name: kaniko
                label: kaniko
                serviceAccount: jenkins
                containers:
                  - name: kaniko
                    image: gcr.io/kaniko-project/executor:debug
                    command: "/busybox/sleep"
                    args: "infinity"
                    ttyEnabled: true
                    resourceRequestCpu: "500m"
                    resourceRequestMemory: "1Gi"
                    resourceLimitCpu: "2"
                    resourceLimitMemory: "4Gi"
                volumes:
                  - secretVolume:
                      secretName: docker-registry-credentials
                      mountPath: /kaniko/.docker

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
