# ArgoCD Application: Jenkins
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mlops-infrastructure

  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.117
    helm:
      releaseName: jenkins
      values: |
        persistence:
          enabled: true
          storageClass: local-path
          size: 20Gi
          accessMode: ReadWriteOnce

        controller:
          serviceType: NodePort
          nodePort: 30080
          admin:
            username: admin
            password: 4k0pYu4JMcZlG8KP
          installPlugins: false
          initGroovyScripts:
            01-create-admin.groovy: |
              import jenkins.model.*
              import hudson.security.*

              def instance = Jenkins.get()
              def adminUser = new File('/run/secrets/additional/chart-admin-username').text.trim()
              def adminPass = new File('/run/secrets/additional/chart-admin-password').text.trim()

              def realm = instance.getSecurityRealm()
              if (!(realm instanceof HudsonPrivateSecurityRealm)) {
                realm = new HudsonPrivateSecurityRealm(false)
                instance.setSecurityRealm(realm)
              }

              def user = realm.getUser(adminUser)
              if (user == null) {
                realm.createAccount(adminUser, adminPass)
              }

              def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
              strategy.setAllowAnonymousRead(false)
              instance.setAuthorizationStrategy(strategy)
              instance.save()

        agent:
          enabled: true
          image:
            registry: docker.io
            repository: jenkins/inbound-agent
            tag: 3345.va_ca_72ea_ce92f-1
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          javaOpts: "-Xmx2g -Xms1g"

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
