# ArgoCD Application: MongoDB
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mlops-infrastructure

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 16.4.6
    helm:
      releaseName: mongodb
      values: |
        architecture: standalone

        image:
          registry: docker.io
          repository: bitnamilegacy/mongodb
          tag: "8.0.13-debian-12-r0"

        global:
          compatibility:
            allowInsecureImages: true

        arbiter:
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

        volumePermissions:
          image:
            registry: docker.io
            repository: bitnamilegacy/os-shell
            tag: "12-debian-12-r40"

        metrics:
          image:
            registry: docker.io
            repository: bitnamilegacy/mongodb-exporter
            tag: "0.44.0-debian-12-r1"

        auth:
          enabled: true
          rootUser: admin
          rootPassword: Moses1749
          database: mlops
          username: moses
          password: Moses1749

        persistence:
          enabled: true
          storageClass: local-path
          size: 10Gi

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi

        service:
          type: NodePort
          nodePorts:
            mongodb: 30017
          port: 27017

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-mongodb

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
