# ArgoCD Application: MySQL
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: mlops-ci
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mlops-infrastructure

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mysql
    targetRevision: 12.2.2
    helm:
      releaseName: mysql
      values: |
        architecture: replication

        auth:
          rootPassword: "Moses1749"
          username: "admin"
          password: "Moses1749"
          replicationPassword: "Moses1749"

        image:
          registry: docker.io
          repository: bitnamilegacy/mysql
          tag: "9.4.0-debian-12-r1"

        primary:
          persistence:
            enabled: true
            storageClass: "local-path"
            size: 10Gi
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          service:
            type: NodePort
            nodePorts:
              mysql: 30306

        secondary:
          replicaCount: 1
          persistence:
            enabled: true
            storageClass: "local-path"
            size: 10Gi
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi

        metrics:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-db

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
