# ArgoCD Application: Namespaces
# Deploys all required namespaces first (sync-wave -1)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: mlops-ci
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: mlops-infrastructure

  source:
    repoURL: https://github.com/MosesDastmard/maine-mlops-infra.git
    targetRevision: HEAD
    path: namespaces

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
