# ArgoCD Application: Services API Backend
# Custom application deployed from local repository
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: mlops-applications

  source:
    # Reference the local repository - UPDATE with your actual repo URL
    repoURL: https://github.com/MosesDastmard/maine-mlops-infra.git  # UPDATE THIS
    targetRevision: HEAD
    path: services/api

  destination:
    server: https://kubernetes.default.svc
    namespace: services-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
