# ArgoCD Application: Strimzi Kafka Operator
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: mlops-ci
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: mlops-infrastructure

  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.44.0
    helm:
      releaseName: strimzi-operator
      values: |
        watchAnyNamespace: false

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-stream

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
