# ArgoCD Application: TimescaleDB
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timescaledb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: mlops-infrastructure

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.4.3
    helm:
      releaseName: timescaledb
      values: |
        global:
          security:
            allowInsecureImages: true

        image:
          registry: docker.io
          repository: timescale/timescaledb-ha
          tag: pg16.11-ts2.24.0-all

        auth:
          postgresPassword: 4k0pYu4JMcZlG8KPTimescaleAdmin!
          username: mlops
          password: 4k0pYu4JMcZlG8KPTimescale!
          database: maine

        primary:
          podAnnotations:
            configChecksum: "v2-pg_cron-enabled"
          service:
            type: NodePort
            nodePorts:
              postgresql: "30432"
          extraVolumes:
            - name: postgresql-run
              emptyDir: {}
          extraVolumeMounts:
            - name: postgresql-run
              mountPath: /var/run/postgresql
            - name: postgresql-config
              mountPath: /bitnami/postgresql/data/postgresql.conf
              subPath: postgresql.conf
          persistence:
            enabled: true
            storageClass: local-path
            size: 50Gi
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          configuration: |
            shared_preload_libraries = 'timescaledb,pg_cron'
            cron.database_name = 'postgres'
            timescaledb.telemetry_level = 'off'
            max_connections = 20
            shared_buffers = 1GB
            effective_cache_size = 3GB
            maintenance_work_mem = 512MB
            work_mem = 32MB
            max_parallel_workers_per_gather = 2
            max_parallel_workers = 4
            wal_buffers = 64MB
            min_wal_size = 512MB
            max_wal_size = 2GB
            max_locks_per_transaction = 1024

        architecture: standalone

        metrics:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-timescaledb

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
