apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: stream-daily-consumer
  namespace: mlops-flink
spec:
  image: dastmard/maine-flink-daily-sale-consumer:latest
  imagePullPolicy: Always
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    state.backend.type: hashmap
    execution.checkpointing.interval: "60000"
    execution.checkpointing.mode: EXACTLY_ONCE
    # Disable HA for simple deployment (no storageDir needed)
    high-availability.type: none
    # Java 17+ module access for Kryo serialization
    env.java.opts.all: "--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED"
    # Prevent read-only filesystem issues
    kubernetes.operator.dynamic.config.enabled: "false"
    web.tmpdir: /tmp
    io.tmp.dirs: /tmp
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1024m"
      cpu: 0.5
    replicas: 1
  taskManager:
    resource:
      memory: "2Gi"
      cpu: 1
    replicas: 1
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-kafka-bootstrap.mlops-kafka.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "maine-sales"
            - name: DB_HOST
              value: "timescaledb-postgresql.mlops-timescaledb.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "maine"
            - name: DB_USER
              value: "mlops"
            - name: DB_PASSWORD
              value: "4k0pYu4JMcZlG8KPTimescale!"
      volumes:
        - name: tmp-volume
          emptyDir: {}
  job:
    jarURI: local:///opt/flink/usrlib/daily-stream-consumer.jar
    parallelism: 1
    upgradeMode: stateless
    entryClass: com.maine.flink.StreamConsumer
